#!/bin/sh -e

./configure \
    --prefix=/usr \
    --disable-java \
    --disable-native-java \
    --disable-csharp \
    --disable-libasprintf \
    --enable-threads=posix \
    --disable-rpath \
    --without-emacs \
    --disable-acl \
    --with-included-glib \
    --with-included-libcroco \
    --without-git \
    --with-included-libxml \
    --with-included-libunistring \
    --disable-openmp \
    --disable-curses \
    --without-examples \
    --enable-nls

make
make DESTDIR="$1" install

