#!/bin/sh -e

# miktex requires harfbuzz to be built with graphite.
# This build tries to add the graphite integration to a system already using
# both freetype and icu in its harfbuzz.

# Point Harfbuzz to the Freetype files.
export CFLAGS="$CFLAGS -I/usr/include/freetype2"
export CXXFLAGS="$CXXFLAGS -I/usr/include/freetype2"
export LDFLAGS="$LDFLAGS -L/usr/lib"

# Will store the built package's files to
# allow us to cherry-pick the graphite related files.
mkdir -p tmp
export DESTDIR="$PWD/tmp"

meson \
    --prefix=/usr \
    -Dpkg_config_path=/usr/lib/pkgconfig \
    -Ddefault_library=both \
    -Dglib=enabled \
    -Dfreetype=enabled \
    -Dicu=enabled \
    -Dicu_builtin=false \
    -Dbenchmark=disabled \
    -Dcairo=disabled \
    -Ddocs=disabled \
    -Dgraphite=enabled \
    . output

ninja -C output
ninja -C output install

install -Dt "$1/usr/include/harfbuzz" tmp/usr/include/harfbuzz/hb-graphite2.h
install -Dt "$1/usr/lib"              tmp/usr/lib/libharfbuzz*
