#!/bin/sh -e

echo "This package is a bit messy and replaces your system harfbuzz libs"
echo "with kiss-alternatives. I wouln't trust me with such important files,"
echo "so be careful, because I might not have updated this properly."
