#!/bin/sh -e

cat << EOF
########################################################################
#                                                                      #
# This package is a bit messy and replaces your system harfbuzz libs   #
# with kiss-alternatives. Be careful when trusting me with such        #
# important files!                                                     #
#                                                                      #
# To build MiKTeX, you'll need to run the following command:           #
#                                                                      #
# $ kiss a | grep graphite-harfbuzz | kiss a -                         #
#                                                                      #
########################################################################
EOF
