#!/bin/sh -e

# hunspell recommends using autoreconf
# autoreconf pulls autopoint, which does gettext stuff (not supported by KISS)
# so we just run each bit it would do without autopoint
libtoolize
aclocal --force -I m4
autoconf -f
autoheader -f
automake -af

./configure \
    --prefix=/usr
make
make DESTDIR="$1" install

# remove non-english manpage (i know, :/)
rm -fr "$1/usr/share/man/hu"
